name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # change if your version is different

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Copy build output to docs folder
        run: |
          rm -rf docs
          mkdir docs
          cp -r build/web/* docs/

      - name: Commit docs folder to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Update GitHub Pages build" || echo "No changes to commit"
          git push origin main
